website/views.py
from difflib import get_close_matches
from email.mime import image
from pdb import post_mortem
from turtle import title
from flask import Blueprint, render_template, request, flash, jsonify
from flask import request, Response
from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from .models import Book
from flask_bootstrap import Bootstrap
from . import db
import json
from datetime import datetime, date
from flask_wtf.file import FileField
from wtforms import StringField, SubmitField, PasswordField, BooleanField, ValidationError, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Length
import keyword
import tkinter
import _tkinter

views = Blueprint('views', __name__)

@views.route('/screen', methods=['GET', 'POST'])
@login_required
def screen():
    return render_template('screen.html',user=current_user)


@views.route('/filterby', methods=['GET', 'POST'])
@login_required
def filterby():

    list_of_authors = []
    authors = Book.query.all()
    for i in authors:
       if i.author not in list_of_authors:
          list_of_authors.append(i.author)



    list_of_years = []
    years = Book.query.all()
    for i in years:
       if i.year not in list_of_years:
          list_of_years.append(i.year)


    return render_template('filterby.html',user=current_user,list_of_authors=list_of_authors, list_of_years= list_of_years)




@views.route('/', methods=['GET'], defaults={"page": 1}) 
@views.route('/<int:page>', methods=['GET'])
@login_required
def view(page):
    page = page
    per_page = 5
    threads = Book.query.paginate(page,per_page,error_out=False)

 

    return render_template("home.html", threads=threads,user=current_user )


@views.route('/books', methods=['GET', 'POST'])
@login_required
def books():
    if request.method == 'POST':

        book = request.form.get('title')
        author= request.form.get('author')
        year = request.form.get('year')
        edition = request.form.get('edition')
        amount= request.form.get('amount')
        image = request.form.get('image')
        

        new_book = Book(title=book,author=author,year=year,edition=edition,image=image,amount=amount)
        db.session.add(new_book)
        db.session.commit()
        flash('Book Added', category='success')

    return render_template("books.html",user=current_user )



@views.route('/update/<int:id>', methods=['GET','POST'])
@login_required
def update(id):
    name_to_update = Book.query.get_or_404(id)
    if request.method == "POST":
        name_to_update.title = request.form.get('title')
        name_to_update.author= request.form.get('author')
        name_to_update.year = request.form.get('year')
        name_to_update.edition = request.form.get('edition')
        name_to_update.amount= request.form.get('amount')
        name_to_update.image = request.form.get('image')

        db.session.commit()
        flash('Book Edited', category='success')

    return render_template("update.html",id=id,name_to_update=name_to_update,user=current_user)    

	
	
@views.route('/delete/<int:id>')
@login_required
def delete(id):
    user_to_delete = Book.query.get_or_404(id)

    db.session.delete(user_to_delete)
    db.session.commit()
    flash('Book deleted Successfully', category='success')

    our_users = Book.query.order_by(Book.title)
    return render_template("screen.html",id=id,our_users=our_users,user_to_delete=user_to_delete,user=current_user)    




@views.route('/search',methods=["POST"])
@login_required
def search():
    title=request.form.get("title").lower()

    list1=[]
    list2 =[]
    list3 =[]
    list4 =[]
    list5 =[]
    list6 =[]
    list7 =[]
    #a = get_close_matches(title,['principito','principe','apple','leah'])
    #print(a)
    results = Book.query.all()
    #print (results)
    for i in results:
        if ((title in i.title.lower() )or (title in i.author.lower())) is True:
            print("entrando if ")
            list1.append(i.title)
            list2.append(i.author)
            list3.append(i.year)
            list4.append(i.edition)
            list5.append(i.image)
            list6.append(i.amount)
            list7.append(i.id)

    return render_template("search.html",count=len(list1), result1 =list1, result2=list2,result3=list3,result4 =list4,result5 =list5,result6 =list6,result7=list7,user=current_user) 
    db.session.commit()



@views.route('/filter',methods=["POST","GET"])
@login_required
def filter():
    option=request.form.get("comp_select")

    list1=[]
    list2 =[]
    list3 =[]
    list4 =[]
    list5 =[]
    list6 =[]
    list7 =[]

    results = Book.query.all()
    for i in results:
        if (option == i.author) :
            list1.append(i.title)
            list2.append(i.author)
            list3.append(i.year)
            list4.append(i.edition)
            list5.append(i.image)
            list6.append(i.amount)
            list7.append(i.id)


    return render_template("filter.html",count=len(list1), result1 =list1, result2=list2,result3=list3,result4 =list4,result5 =list5,result6 =list6,result7=list7,user=current_user)



@views.route('/filterYear',methods=['GET', 'POST'])
@login_required
def filterYear():
    option=request.form.get("years")

    list1=[]
    list2 =[]
    list3 =[]
    list4 =[]
    list5 =[]
    list6 =[]
    list7 =[]

    results = Book.query.all()
    for i in results:
        if (option==i.year) :
            list1.append(i.title)
            list2.append(i.author)
            list3.append(i.year)
            list4.append(i.edition)
            list5.append(i.image)
            list6.append(i.amount)
            list7.append(i.id)


    return render_template("filterYear.html",count=len(list1), result1 =list1, result2=list2,result3=list3,result4 =list4,result5 =list5,result6 =list6,result7=list7,user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">


    <!-- Bootstrap core CSS -->
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='vendor/bootstrap/css/bootstrap.min.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/fontawesome.css') }}">


    <!-- Additional CSS Files -->
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/fontawesome.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/templatemo-cyborg-gaming.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/owl.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/animate.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/fontawesome.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/fontawesome.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='assets/css/fontawesome.css') }}">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>

   <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
     
        <!-- ***** Header Area Start ***** -->
        <header class="header-area header-sticky">
          <div class="container">
              <div class="row">
                  <div class="col-12">
                      <nav class="main-nav">

                          
                          <!-- ***** Logo Start ***** -->
                          <a href="/" class="logo">
                              <img src= "{{ url_for('static',filename='assets/images/logo.png') }}" alt="">
                          </a>
                          <!-- ***** Logo End ***** -->
                          <!-- ***** Search End ***** -->
                          
                         
                          <!-- ***** Search End ***** -->
                          <!-- ***** Menu Start ***** -->
                          <ul class="nav">
                            {% if user.is_authenticated %}
                         
                              <li> <a class="nav-item nav-link" id="screen" href="/screen">Home</a></li>
                              <li><a class="nav-item nav-link" id="home" href="/">My Books</a<li>
                              <li><a class="nav-item nav-link" id="books" href="/books">Add Book</a></li>
                              <li><a class="nav-item nav-link" id="filterby" href="/filterby">Filter by</a></li>
                              <div class="search-input">
                                <form id="search" method="POST" action="{{'search'}} ">
                                  <input  type='text' name="title" placeholder="Enter Title or Author of Book"  id='searchText'  onkeypress="handle" />
                                  <i class="fa fa-search"></i>
                                </form>
                              </div>
                              <li><a href="/logout" id= "logout">Logout <img src="{{ url_for('static',filename='assets/images/profile-header.jpg') }}" alt=""></a></li>

                              {% else %}
                              <li><a class="nav-item nav-link" id="login" href="/login">Login</a></li>
                              <li><a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a></li>
                              {% endif %}
                          </ul>   
                          <a class='menu-trigger'>
                              <span>Menu</span>
                          </a>
                          <!-- ***** Menu End ***** -->
                      </nav>
                      {% with messages = get_flashed_messages(with_categories=true) %} {% if
                        messages %} {% for category, message in messages %} {% if category ==
                        'error' %}
                        <div class="alert alert-danger alter-dismissable fade show" role="alert">
                          {{ message }}
                          <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        {% else %}
                        <div class="alert alert-success alter-dismissable fade show" role="alert">
                          {{ message }}
                          <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        {% endif %} {% endfor %} {% endif %} {% endwith %}
                  </div>
              </div>
          </div>
        </header>
      
       

        <!-- ***** Header Area End ***** -->

        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="page-content">{% block content %} {% endblock %}

              </div>
            </div>
          </div>
        </div>
        <footer>
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <p>Copyright © 2022 <a href="#">Andres Cusirramos</a>  All rights reserved. 
                
                <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a>  Distributed By <a href="https://themewagon.com" target="_blank" >ThemeWagon</a></p>
              </div>
            </div>
          </div>
        </footer>
        <!-- Scripts -->
        <!-- Bootstrap core JavaScript -->
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='vendor/jquery/jquery.min.js') }}">

        <script src=href= "{{ url_for('static',filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
        <script src=href= "{{ url_for('static',filename='assets/js/isotope.min.js') }}"></script>
        <script src=href= "{{ url_for('static',filename='assets/js/owl-carousel.js') }}"></script>
        <script src=href= "{{ url_for('static',filename='assets/js/tabs.js') }}"></script>
        <script src=href= "{{ url_for('static',filename='assets/js/popup.js') }}"></script>
        <script src=href= "{{ url_for('static',filename='assets/js/custom.js') }}"></script>

        </body>
</html>

website/templates/books.html
{% extends "base.html" %} {% block title %}Add a Book{% endblock %} {% block content
    %}
    <h1 align="center">Add Books</h1>
    <form  enctype="multipart/form-data"  method="POST"  class="needs-validation" novalidate>
        <div class="form-row">
          <div class="col-md-4 mb-3">
            <label style="color:white" for="validationTooltip01">Title</label>
            <input name="title" id="title" type="text" class="form-control" id="validationTooltip01" placeholder="Title" required></input>
            <div class="valid-tooltip">
              Looks good!
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label style="color:white" for="validationTooltip02">Author</label>
            <input name="author" id="author" type="text" class="form-control" id="validationTooltip02" placeholder="Author" required></input>
            <div class="valid-tooltip">
              Looks good!
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label  style="color:white" for="validationTooltip02">Year</label>
            <input name="year" id="year" type="number" class="form-control" id="validationTooltip02" placeholder="Year" required></input>
            <div class="valid-tooltip">
              Looks good!
            </div>
          </div>
         
        </div>
        <div class="form-row">
          <div class="col-md-6 mb-3">
            <label style="color:white"  for="validationTooltip03">Link of the Cover</label>
            <input name="image" id="image" type="text" class="form-control" id="validationTooltip03" placeholder="Link of the Cover" required>
            <div class="invalid-tooltip">
              Please provide a Link of the cover .
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label  style="color:white" for="validationTooltip04">Edition</label>
            <input name="edition" id="edtion" type="number" class="form-control" id="validationTooltip04" placeholder="Edition" required>
            <div class="invalid-tooltip">
              Please provide a Edition.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label style="color:white" for="validationTooltip05">Stock</label>
            <input name="amount" id="amount" type="number" class="form-control" id="validationTooltip05" placeholder="Stock" required>
            <div class="invalid-tooltip">
              Please provide a stock.
            </div>
          </div>
        </div>
        <button class="btn btn-primary" type="submit">Submit form</button>
      </form>
      

{% endblock %}

website/templates/filter.html
{% extends "base.html" %} {% block title %}Filter a Book{% endblock %} {% block content%}

      <div class="gaming-library">
        <div class="col-lg-12">
          <div class="heading-section">
            <h4><em>Result</em> Of The Filter by Author</h4>
          </div>
          {% for i in range(count) %}
          <div class="item">
            <ul>
              <li><img src="{{result5[i]}}" alt="" class="templatemo-item"></li>
              <li><h4>{{result1[i]}}</h4><span>{{result2[i]}}</span></li>
              <li><h4>Year</h4><span>{{result3[i]}}</span></li>
              <li><h4>Edition</h4><span>{{result4[i]}}</span></li>
              <li><h4>Amount</h4><span>{{result6[i]}}</span></li>
              <li><form action="{{url_for('views.delete', id = result7[i])}}">
                <button type="submit" class="btn btn-outline-danger">X</button>
              </form></li>
              <li><form action="{{url_for('views.update', id = result7[i])}}">
                <button type="submit" class="btn btn-outline-warning">Edit
                </button>
             </form></li>
            </ul>
          </div>
          {% endfor %}  



{% endblock %}

website/templates/filterYear.html
{% extends "base.html" %} {% block title %}Filter a Book{% endblock %} {% block content%}

      <div class="gaming-library">
        <div class="col-lg-12">
          <div class="heading-section">
            <h4><em>Result</em> Of The Filter by Year</h4>
          </div>
          {% for i in range(count) %}
          <div class="item">
            <ul>
              <li><img src="{{result5[i]}}" alt="" class="templatemo-item"></li>
              <li><h4>{{result1[i]}}</h4><span>{{result2[i]}}</span></li>
              <li><h4>Year</h4><span>{{result3[i]}}</span></li>
              <li><h4>Edition</h4><span>{{result4[i]}}</span></li>
              <li><h4>Amount</h4><span>{{result6[i]}}</span></li>
              <li><form action="{{url_for('views.delete', id = result7[i])}}">
                <button type="submit" class="btn btn-outline-danger">X</button>
              </form></li>
              <li><form action="{{url_for('views.update', id = result7[i])}}">
                <button type="submit" class="btn btn-outline-warning">Edit
                </button>
             </form></li>
            </ul>
          </div>
          {% endfor %}  



{% endblock %}

website/templates/filterby.html
{% extends "base.html" %} {% block title %}Filter by Author{% endblock %} {% block content
    %}
    <h1 align="center">Filter by Author</h1>


    <form class="form-inline" method="POST" action="{{ url_for('views.filter') }}">
      <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"></span>
                <select name="comp_select" class="selectpicker form-control">
                  <option value="none">Filter books by Author</option>
                  {%for i in list_of_authors%}
                  <option value="{{i}}">{{i}}</option>
                  {% endfor %}
                </select>
        </div>
        <button type="submit" class="main-button">Filter by Author</button>
      </div>
    </form>

    <form class="form-inline" method="POST" action="{{ url_for('views.filterYear') }}">
      <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"></span>
                <select name="years" class="selectpicker form-control">
                  <option value="none">Filter books by year</option>
                  {%for i in list_of_years%}
                  <option value="{{i}}">{{i}}</option>
                  {% endfor %}
                </select>
        </div>
        <button type="submit" class="main-button">Filter by Year</button>
      </div>
    </form>



    

    
  {% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1 align="center">Books</h1>


    <div class="gaming-library">
      <div class="col-lg-12">
        <div class="heading-section">
          <h4><em>Your</em> Books</h4>
        </div>
        {% for book in threads.items %}
        <div class="item">
          <ul>
            <li><img src="{{book.image}}" alt="" class="templatemo-item"></li>
            <li><h4>{{book.title}}</h4><span>{{book.author}}</span></li>
            <li><h4>Year</h4><span>{{book.year}}</span></li>
            <li><h4>Edition</h4><span>{{book.edition}}</span></li>
            <li><h4>Amount</h4><span>{{book.amount}}</span></li>
            <li><form action="{{url_for('views.delete', id = book.id)}}">
              <button type="submit" class="btn btn-outline-danger">X</button>
            </form></li>
            <li><form action="{{url_for('views.update', id = book.id)}}">
              <button type="submit" class="btn btn-outline-warning">Edit
              </button>
           </form></li>

         
          </ul>
        </div>
        {% endfor %}
  </br>
    <nav aria-label="Page navigation example" style="display: inline-block; list-style-type: none;">
      <ul class="pagination">
          {% if threads.has_prev %}
            <li class="page-item"> <a class="page-link" href="{{ url_for('views.view', page=threads.prev_num) }}">Previous</a></li>
          {% else %}
            <li class="page-item"><a class="page-link btn disabled" href="#">Previous</a></li>
          {% endif %}
      </br>
          {% if threads.has_next %}
            <li class="page-item"> <a class="page-link" href="{{ url_for('views.view', page=threads.next_num) }}">Next</a></li>
          {% else %}
            <li class="page-item"><a class="page-link btn disabled" href="#">Next</a></li>
          {% endif %}

      </ul>
    </nav>
  {% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <h3 align="center">Login</h3>
    

    <section class="vh-100">
      <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-9 col-lg-6 col-xl-5">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
              class="img-fluid" alt="Sample image">
          </div>
          <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
            <form method="POST">



              <!-- Email input -->
              <div class="form-outline mb-4">
                <input type="email" id="email" name="email"class="form-control form-control-lg"
                  placeholder="Enter a valid email address" />
              </div>


              <!-- Password input -->
              <div class="form-outline mb-3">
                <input type="password" id="password" name="password" class="form-control form-control-lg"
                  placeholder="Enter password" />
              </div>
    
              <div class="d-flex justify-content-between align-items-center">
    
              <div class="text-center text-lg-start mt-4 pt-2">
                <button type="submit" class="btn btn-primary btn-lg"
                  style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="/sign-up"
                    class="link-danger">Register</a></p>
              </div>
    
            </form>
          </div>
        </div>
      </div>
  
     
    </section>


    
    {% endblock %}

website/templates/screen.html
{% extends "base.html" %} {% block title %}Main{% endblock %} {% block content
    %}
    <div class="container">
        <div class="row">
 
              <!-- ***** Start Stream Start ***** -->
              <div class="start-stream">
                <div class="col-lg-12">
                  <div class="heading-section">
                    <h4><em>Gestor</em> Biblioteca Personal</h4>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="item">
                        <div class="icon">
                          <img   src=  "{{ url_for('static',filename='assets/images/service-01.jpg') }}" alt="" style="max-width: 60px; border-radius: 50%;">
                        </div>
                        <h4>Almacena tus libros favoritos</h4>
                        <p>Guarda tus libros por Titulo, Autor, Año, Edicion, Imagen y Cantidad.</p>
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="item">
                        <div class="icon">
                          <img src= "{{ url_for('static',filename='assets/images/service-02.jpg') }}"  alt="" style="max-width: 60px; border-radius: 50%;">
                        </div>
                        <h4>Listado Paginado</h4>
                        <p>Listado de los libros paginado, con la posibilidad de modificar, eliminar y agregar nuevos libros.</p>
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="item">
                        <div class="icon">
                          <img src=  "{{ url_for('static',filename='assets/images/service-03.jpg') }}"  alt="" style="max-width: 60px; border-radius: 50%;">
                        </div>
                        <h4>Busqueda</h4>
                        <p>Se puede realizar una busqueda por texto y aplicar el filtro por autor o titulo.</p>
                      </div>
                    </div>
                    <div class="col-lg-12">
                      <div class="main-button">
                        <a href="/">My Books</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- ***** Start Stream End ***** -->
    
              <!-- ***** Live Stream Start ***** -->
              <div class="live-stream">
                <div class="col-lg-12">
                  <div class="heading-section">
                    <h4><em>Most Popular</em> Books</h4>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-3 col-sm-6">
                    <div class="item">
                      <div class="thumb">
                        <img src=  "{{ url_for('static',filename='assets/images/stream-01.jpg') }}"  alt="">
                        <div class="hover-effect">
                          <div class="content">
                            <div class="live">
                              <a href="#">Live</a>
                            </div>
                            <ul>
                       
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="down-content">
                        <div class="avatar">
                          <img src=   "{{ url_for('static',filename='assets/images/avatar-01.jpg') }}"    alt="" style="max-width: 46px; border-radius: 50%; float: left;">
                        </div>
                        <span><i class="fa fa-check"></i> J.K.Rowling</span>
                        <h4>Harry Potter</h4>
                      </div> 
                    </div>
                  </div>
                  <div class="col-lg-3 col-sm-6">
                    <div class="item">
                      <div class="thumb">
                        <img src=   "{{ url_for('static',filename='assets/images/stream-02.jpg') }}"  alt="">
                        <div class="hover-effect">
                          <div class="content">
                            <div class="live">
                              <a href="#">Live</a>
                            </div>
                            <ul>

                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="down-content">
                        <div class="avatar">
                          <img src=   "{{ url_for('static',filename='assets/images/avatar-02.jpg') }}"  alt="" style="max-width: 46px; border-radius: 50%; float: left;">
                        </div>
                        <span><i class="fa fa-check"></i> Suzanne Collins</span>
                        <h4>Hunger Games</h4>
                      </div> 
                    </div>
                  </div>
                  <div class="col-lg-3 col-sm-6">
                    <div class="item">
                      <div class="thumb">
                        <img src= "{{ url_for('static',filename='assets/images/stream-03.jpg') }}"   alt="">
                        <div class="hover-effect">
                          <div class="content">
                            <div class="live">
                              <a href="#">Live</a>
                            </div>
                            <ul>
      
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="down-content">
                        <div class="avatar">
                          <img src=   "{{ url_for('static',filename='assets/images/avatar-03.jpg') }}"   alt="" style="max-width: 46px; border-radius: 50%; float: left;">
                        </div>
                        <span><i class="fa fa-check"></i> Julio Verne</span>
                        <h4> Viaje al centro de la Tierra</h4>
                      </div> 
                    </div>
                  </div>
                  <div class="col-lg-3 col-sm-6">
                    <div class="item">
                      <div class="thumb">
                        <img src=   "{{ url_for('static',filename='assets/images/stream-04.jpg') }}" alt="">
                        <div class="hover-effect">
                          <div class="content">
                            <div class="live">
                              <a href="#">Live</a>
                            </div>
                            <ul>

                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="down-content">
                        <div class="avatar">
                          <img src=     "{{ url_for('static',filename='assets/images/avatar-04.jpg') }}" alt="" style="max-width: 46px; border-radius: 50%; float: left;">
                        </div>
                        <span><i class="fa fa-check"></i> Cory Althoff</span>
                        <h4>The self-taught Computer Scientist</h4>
                      </div> 
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="main-button">
                      <a href="/books">Agrega mas libros</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- ***** Live Stream End ***** -->
    
    
        </div>
      </div>
      
  
    
    {% endblock %}

website/templates/search.html
{% extends "base.html" %} {% block title %}Search a Book{% endblock %} {% block content%}

      <div class="gaming-library">
        <div class="col-lg-12">
          <div class="heading-section">
            <h4><em>Result</em> Of The Search</h4>
          </div>
          {% for i in range(count) %}
          <div class="item">
            <ul>
              <li><img src="{{result5[i]}}" alt="" class="templatemo-item"></li>
              <li><h4>{{result1[i]}}</h4><span>{{result2[i]}}</span></li>
              <li><h4>Year</h4><span>{{result3[i]}}</span></li>
              <li><h4>Edition</h4><span>{{result4[i]}}</span></li>
              <li><h4>Amount</h4><span>{{result6[i]}}</span></li>
              <li><form action="{{url_for('views.delete', id = result7[i])}}">
                <button type="submit" class="btn btn-outline-danger">X</button>
              </form></li>
              <li><form action="{{url_for('views.update', id = result7[i])}}">
                <button type="submit" class="btn btn-outline-warning">Edit
                </button>
             </form></li>
            </ul>
          </div>
          {% endfor %}  



{% endblock %}